export enum InformationSourceType {
    LABELING_FUNCTION = "LABELING_FUNCTION",
    ACTIVE_LEARNING = "ACTIVE_LEARNING",
    PRE_COMPUTED = "PRE_COMPUTED",
    ZERO_SHOT = "ZERO_SHOT",
    CROWD_LABELER = "CROWD_LABELER"
}

export enum DisplayGraphs {
    ALL,
    CONFUSION_MATRIX = "CONFUSION_MATRIX",
    INTER_ANNOTATOR = "INTER_ANNOTATOR",
    LABEL_DISTRIBUTION = "LABEL_DISTRIBUTION",
    CONFIDENCE_DISTRIBUTION = "CONFIDENCE_DISTRIBUTION",
}

export enum LabelSource {
    MANUAL = "MANUAL",
    WEAK_SUPERVISION = "WEAK_SUPERVISION",
    INFORMATION_SOURCE = "INFORMATION_SOURCE",
    MODEL_CALLBACK = "MODEL_CALLBACK",
}
